channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.2
- pip:
  - mlflow==2.15.0
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==6.0.0
  - scikit-learn==1.5.1
  - scipy==1.14.0
  - xgboost==2.1.0
name: mlflow-env
